[CmdletBinding()]
param(
    [string]$DatabaseName = "SqlWorkflowMonitor_Dev",
    [string]$OutputPath = "SqlWorkflowMonitor/SqlScripts/Install.sql",
    [switch]$VerifyOnly
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

function Normalize-LineEndings {
    param(
        [Parameter(Mandatory)]
        [string]$Value
    )

    # Normalización intermedia a LF.
    $normalized = $Value.Replace("`r`n", "`n")
    $normalized = $normalized.Replace("`r", "`n")

    return $normalized
}

if ($DatabaseName -notmatch '^[A-Za-z0-9_]+$') {
    throw "DatabaseName solo puede contener letras, números y guion bajo."
}

$repositoryRoot = Split-Path -Parent $PSScriptRoot
$sqlDirectory = Join-Path $repositoryRoot "SqlWorkflowMonitor/SqlScripts"
$outputFullPath = Join-Path $repositoryRoot $OutputPath

$scriptFiles = @(
    Get-ChildItem -Path $sqlDirectory -File -Filter "*.sql" |
        Where-Object {
            $_.Name -match '^\d{3}_.*\.sql$'
        } |
        Sort-Object Name
)

if ($scriptFiles.Count -eq 0) {
    throw "No se encontraron scripts SQL incrementales."
}

for ($index = 0; $index -lt $scriptFiles.Count; $index++) {

    $expectedPrefix = "{0:D3}_" -f ($index + 1)

    if (-not $scriptFiles[$index].Name.StartsWith(
            $expectedPrefix,
            [System.StringComparison]::Ordinal)) {

        throw "La secuencia SQL no es contigua. Se esperaba $expectedPrefix y se encontró $($scriptFiles[$index].Name)."
    }
}

$parts = New-Object 'System.Collections.Generic.List[string]'

$parts.Add("/*")
$parts.Add("  SqlWorkflowMonitor consolidated database installer")
$parts.Add("  Generated by scripts/Build-InstallSql.ps1")
$parts.Add("  Do not edit this file directly.")
$parts.Add("*/")
$parts.Add("")

for ($index = 0; $index -lt $scriptFiles.Count; $index++) {

    $scriptFile = $scriptFiles[$index]

    $content = [System.IO.File]::ReadAllText($scriptFile.FullName)

    # Evitar que el resultado dependa de LF/CRLF del sistema operativo.
    $content = Normalize-LineEndings $content

    $content = $content.Replace(
        "SqlWorkflowMonitor_Dev",
        $DatabaseName
    )

    $content = $content.TrimEnd("`n")

    $parts.Add(
        "/* ===== BEGIN FILE: $($scriptFile.Name) ===== */"
    )

    $parts.Add($content)

    $parts.Add(
        "/* ===== END FILE: $($scriptFile.Name) ===== */"
    )

    if ($index -lt ($scriptFiles.Count - 1)) {
        $parts.Add("")
    }
}

# Construcción canónica interna.
$generatedLf = ($parts -join "`n") + "`n"

# El archivo físico SQL se escribe con CRLF.
$generatedCrLf = $generatedLf.Replace(
    "`n",
    "`r`n"
)

if ($VerifyOnly) {

    if (-not (Test-Path $outputFullPath)) {
        throw "No existe el instalador consolidado: $outputFullPath"
    }

    $existing = [System.IO.File]::ReadAllText(
        $outputFullPath
    )

    # La validación compara contenido normalizado.
    # LF y CRLF no deben producir falsos errores.
    $existingNormalized = Normalize-LineEndings $existing
    $generatedNormalized = Normalize-LineEndings $generatedCrLf

    if ($existingNormalized -ne $generatedNormalized) {
        throw "Install.sql no coincide con los scripts incrementales. Ejecute scripts/Build-InstallSql.ps1."
    }

    Write-Host "Install.sql está sincronizado con $($scriptFiles.Count) scripts incrementales."
    exit 0
}

$outputDirectory = Split-Path -Parent $outputFullPath

New-Item `
    -ItemType Directory `
    -Path $outputDirectory `
    -Force |
Out-Null

$utf8WithoutBom =
    New-Object System.Text.UTF8Encoding($false)

[System.IO.File]::WriteAllText(
    $outputFullPath,
    $generatedCrLf,
    $utf8WithoutBom
)

Write-Host "Generado: $outputFullPath"
Write-Host "Scripts incluidos: $($scriptFiles.Count)"
Write-Host "Base de datos: $DatabaseName"
